# fly.toml app configuration file generated for mb-scanner on 2026-06-07T11:48:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mb-scanner'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/data'
  PORT = '3000'

[[mounts]]
  source = 'mb_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
